channels:
  - conda-forge

dependencies:
  - python=3.11.0
  - pip=23.2.1
  - pip:
      - robotframework-browser==16.3.0
      - robotframework-pabot==2.16.0
      - robotframework-faker==5.0.0

rccPostInstall:
  - rfbrowser init